### ISSUE TITLE
Roadmap: parsnip support for sparse tibbles

### ISSUE THREAD

**Issue by EmilHvitfeldt** [tidymodels/parsnip#1125]
What we need:

- [x] `fit()` to take sparse tibbles as data https://github.com/tidymodels/parsnip/pull/1165
- [x] `fit()` to take {Matrix} sparse matrix as data https://github.com/tidymodels/parsnip/pull/1121
  - turn them into sparse tibbles early
- [x] `predict()` to take sparse tibbles as data https://github.com/tidymodels/parsnip/pull/1167
- [x] `predict()` to take {Matrix} sparse matrix as data https://github.com/tidymodels/parsnip/pull/1167
  - turn them into sparse tibbles early
- [x] look into if we document which engines are sparse friendly https://github.com/tidymodels/parsnip/pull/1171
- [x] special cases for some model types https://github.com/tidymodels/parsnip/pull/1173
  - {xgboost} with `xgboost::xgb.DMatrix()` and `xgb_train()` (only special case engine that allows sparse data)
- [x] Better error if sparse matrix is used with `fit()` https://github.com/tidymodels/parsnip/pull/1174
- [x] Make sure all error messages are piped through correctly https://github.com/tidymodels/parsnip/pull/1174

I think we could use a `option()` of some kind to unit test that the data passed is passed around in a way that keeps the sparsity.

Adding all of this will give us
- standalone usage of sparse matrices in {parsnip} 
- everything it needs to be able to work with the rest of {tidymodels} in regards to sparse tibbles
